MODEL:
  TYPE: 'RegressFlow'
  PRETRAINED: ''
  BACKBONE:
    TYPE: 'ResNet'
    NUM_LAYERS: 50
  NUM_FC_FILTERS:
  - -1
  HIDDEN_LIST: -1

DATASET:
  TRAIN:
    TYPE: 'COCO'
    ROOT: '/home/xyh/dataset/coco/'
    IMG_PREFIX: 'images'
    ANN: 'annotations/person_keypoints_train2017.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 45
      SCALE_FACTOR: 0.25
      NUM_JOINTS_HALF_BODY: 3
      PROB_HALF_BODY: 0.3
  VAL:
    TYPE: 'COCO'
    ROOT: '/home/xyh/dataset/coco/'
    IMG_PREFIX: 'images'
    ANN: 'annotations/person_keypoints_val2017.json'
  TEST:

DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
  NEED_HEATMAP: true
  NEED_COORD: true
  NEED_CENTERMAP: false

TRAIN:
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  BATCH_SIZE: 64
  OPTIMIZER: 'adam'
  LR: 0.0005
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200

INFERENCE:
  PRETRAINED: './models/regressflow_resnet_best.pth'

WORK:
  LOG: "./logs/regressflow_resnet_coco.log"
  BEST_MODEL: './pretrained/regressflow_resnet_best.pth'
  FINAL_MODEL: './pretrained/regressflow_resnet_final.pth'
